import { mkdir, readdir, rename, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import { config } from './config.js';

export const liveDir = config.backupDir;
export const trashDir = path.join(config.backupDir, 'trash');
export const uploadDir = path.join(config.backupDir, 'uploads');

export async function ensureDirs() {
  await mkdir(liveDir, { recursive: true });
  await mkdir(trashDir, { recursive: true });
  await mkdir(uploadDir, { recursive: true });
}

// Backup filenames are always generated by this app (or sanitized on
// upload) — reject anything else so path traversal / arbitrary reads or
// writes outside the backup directory are impossible even if a future
// caller forgets to validate first.
const SAFE_NAME = /^[A-Za-z0-9._-]+\.sql(\.gz)?$/;

export function isSafeName(name) {
  return typeof name === 'string' && SAFE_NAME.test(name) && !name.includes('..');
}

export function dateStamp(d = new Date()) {
  return d.toISOString().slice(0, 10); // YYYY-MM-DD
}

export function timeStamp(d = new Date()) {
  return d.toISOString().replace(/[:.]/g, '-').slice(0, 19); // YYYY-MM-DDTHH-MM-SS
}

function humanSize(bytes) {
  const units = ['B', 'KB', 'MB', 'GB'];
  let n = bytes;
  let i = 0;
  while (n >= 1024 && i < units.length - 1) { n /= 1024; i += 1; }
  return `${n.toFixed(i === 0 ? 0 : 1)} ${units[i]}`;
}

async function listDir(dir, location) {
  let names;
  try {
    names = await readdir(dir);
  } catch {
    return [];
  }
  const items = [];
  for (const name of names) {
    if (!isSafeName(name)) continue;
    const full = path.join(dir, name);
    const st = await stat(full).catch(() => null);
    if (!st || !st.isFile()) continue;
    items.push({
      name,
      location,
      sizeBytes: st.size,
      sizeHuman: humanSize(st.size),
      mtime: st.mtime.toISOString(),
    });
  }
  items.sort((a, b) => b.mtime.localeCompare(a.mtime));
  return items;
}

export async function listBackups() {
  const [live, trash] = await Promise.all([
    listDir(liveDir, 'live'),
    listDir(trashDir, 'trash'),
  ]);
  return { live, trash };
}

export async function moveToTrash(name) {
  if (!isSafeName(name)) throw new Error('Invalid backup name');
  await rename(path.join(liveDir, name), path.join(trashDir, name));
}

export async function restoreFromTrash(name) {
  if (!isSafeName(name)) throw new Error('Invalid backup name');
  await rename(path.join(trashDir, name), path.join(liveDir, name));
}

export async function deleteFromTrash(name) {
  if (!isSafeName(name)) throw new Error('Invalid backup name');
  await rm(path.join(trashDir, name));
}

/** Soft-delete anything past retentionDays, then hard-delete anything in
 * trash past trashRetentionDays. A wrong retention setting only costs a
 * delayed cleanup, never an instant permanent loss. */
export async function pruneOldBackups() {
  const now = Date.now();
  const { live, trash } = await listBackups();

  for (const item of live) {
    const ageDays = (now - new Date(item.mtime).getTime()) / 86_400_000;
    if (ageDays > config.retentionDays) {
      await moveToTrash(item.name).catch(() => {});
    }
  }
  for (const item of trash) {
    const ageDays = (now - new Date(item.mtime).getTime()) / 86_400_000;
    if (ageDays > config.trashRetentionDays) {
      await deleteFromTrash(item.name).catch(() => {});
    }
  }
}
